stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/Crop_recommendation.csv
    outs:
      - data/raw_data.pkl
    params:
      - data.source

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw_data.pkl
    outs:
      - data/processed_data.pkl
    params:
      - preprocessing.drop_duplicates
      - preprocessing.fill_missing_strategy
      - preprocessing.encode_categorical
      - preprocessing.target_column

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed_data.pkl
    outs:
      - data/features.pkl
      - data/target.pkl
    params:
      - preprocessing.target_column

  model_training:
    cmd: python src/model_engineering.py
    deps:
      - src/model_engineering.py
      - data/features.pkl
      - data/target.pkl
    outs:
      - models/model.pkl
      - data/test_features.pkl
      - data/test_target.pkl
    params:
      - model.algorithm
      - model.n_estimators
      - model.max_depth
      - model.min_samples_split
      - model.min_samples_leaf
      - model.max_features
      - model.max_leaf_nodes
      - model.min_impurity_decrease
      - model.bootstrap
      - model.oob_score
      - model.criterion
      - model.random_state
      - training.test_size
      - training.random_state

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/test_features.pkl
      - data/test_target.pkl
    outs:
      - plots/confusion_matrix.png
      - plots/feature_importance.png
    metrics:
      - metrics/metrics.json
    params:
      - evaluation.cv_folds
      - evaluation.metrics_file