# Parameters for ML Pipeline
data:
  source: "data/Crop_recommendation.csv"
  processed: "data/processed_data.csv"

preprocessing:
  drop_duplicates: true
  fill_missing_strategy: "median"
  encode_categorical: true
  target_column: "label"

model:
  algorithm: "RandomForest"
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: true
  oob_score: false
  criterion: "gini"
  random_state: 42
  
training:
  test_size: 0.2
  random_state: 42
  
evaluation:
  cv_folds: 5
  metrics_file: "metrics/metrics.json"
  
outputs:
  model_file: "models/model.pkl"
  feature_importance_plot: "plots/feature_importance.png"
  confusion_matrix_plot: "plots/confusion_matrix.png"